# Generated by Django 3.1.6 on 2021-05-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='oxygen_cylinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=50)),
                ('person_name', models.CharField(max_length=50, null=True)),
                ('contact', models.BigIntegerField()),
                ('verified_status', models.CharField(max_length=30)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
