# Generated by Django 3.1.6 on 2021-05-07 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oxygen', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='oxygen_cylinder',
            new_name='OxygenCylinder',
        ),
    ]
